apiVersion: v1
kind: Secret
metadata:
  name: chat-app
  namespace: chat-app
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjME16YzBPRFEwTnl3aWFXRjBJam94TnpRek56UTRORFEzZlEuX1FEZ1pnWFFNeXZQR1ZaeUlvYUR4MU1MbFBBNjkzcnk4Z2MxbXN5LVViQQo=
